Feature/add decision maker
mario-r99/jarvil pull request #90
Opened 2021-07-05 10:09 UTC by densalzmann

2021-07-05 11:17 UTC, mario-r99 requested changes

2021-07-05 11:17 UTC, mario-r99 commented on services/decision-maker/executor.py
> +            mqtt_data["airfilter"] = json.loads(decoded_payload)["airfilter"]
Are you going to send these states also from the climate service? If you do so, I think it will end in a calling loop:
1. AI planner sends new state over MQTT
2. Actor changes state based on MQTT
3. Actor publishes new actor state over MQTT
4. AI planner gets new state update and repeats cycle till it crashes

2021-07-05 11:40 UTC, densalzmann commented on docker/development/docker-compose.yml
> -    volumes:
They is a dublecate volumes. See above 63 line

2021-07-05 11:41 UTC, densalzmann commented on services/decision-maker/domain.pddl
> +(define
When deleting the problem.pddl file, it receives an error.

2021-07-05 11:41 UTC, densalzmann commented on services/decision-maker/problem.pddl
> +(define
When deleting the problem.pddl file, it receives an error.

2021-07-05 11:42 UTC, densalzmann commented on services/decision-maker/subscriber.py
> +import paho.mqtt.client as mqtt
Nope, will drop it by the next push

2021-07-05 11:45 UTC, densalzmann commented on services/decision-maker/executor.py
> +            mqtt_data["airfilter"] = json.loads(decoded_payload)["airfilter"]
Nope, i habe include the logic in the planer to handle this case. But we will have to test it after all will be implemented from the climate-service side

2021-07-05 11:55 UTC, mario-r99 commented on services/decision-maker/domain.pddl
> +(define
Ok but you don't know why?

2021-07-05 11:57 UTC, mario-r99 commented on services/decision-maker/executor.py
> +            mqtt_data["airfilter"] = json.loads(decoded_payload)["airfilter"]
But you send additional mqtt messages from the AI planner for the thermostat, light...? I think that will result in the same problem

2021-07-07 16:52 UTC, mario-r99 approved these changes

2021-07-07 16:52 UTC, merged